### PR TITLE
discuss current solution for #49

### PR DESCRIPTION
**Pull request by andreineculau**
~This is a reverse PR meaning the code (a possible solution to #49) is already on master (for practical reasons; I couldn't test end-to-end) so left and right pane are switched. Left pane = new code, right pane = old code.~ Reverted on master.

Example - Travis CI build https://travis-ci.com/tobiipro/support-firecloud/jobs/169761869
printed artifact links in "after_script" phase, all the way down on log line 2519-2520

* 11:06:58 [INFO] View job artifacts on Github: https://github.com/tobiipro/support-firecloud/tree/2430bb57d19cf0d5fba47b5905d92705ab215307
* 11:06:58 [INFO] View job artifacts on S3: https://s3.console.aws.amazon.com/s3/buckets/infra-attentionpanel-com-eu-west-1/ci/169761869/

## Highlights
* Difference in permissions
  * The github link is accessible to all those that have read access to the repo. This also means that whoever did a "git push", can just fetch the artifacts locally (see example command in the NOTE below)
  * The s3 link is accessible to all those that have list access to the bucket (atexdev users).
* UI - way easier to browse and read on github
* Auth - github requires credentials (travis encrypted GH_TOKEN), while S3 requires none (public-writes)
  * what this means is that it's not possible to upload to github for PRs (PR builds don't have access to secrets, and thus not to GH_TOKEN either)
* Life cycle - artifacts have a time-bomb on S3, but not on github (maybe possible via github actions?); but on the upside

NOTE: "git clone/fetch/pull" does not automatically download the job artifacts. One has to either configure git to do so, or call `git clone fetch refs/jobs/169761869 && git checkout FETCH_HEAD` if it's a one time thing "check the job artifacts and get out"

## TODO

* [x] add docs
* [x] maybe set content-type: 'text/plain' for S3 uploads, so that at least they can be opened in the browser, rather than downloaded
* [x] maybe use 'infra-tobiicloud-com-eu-west-1' instead?

### CODE REVIEW

**Comment by IanSavchenko** [comment]
Yes, GitHub solution looks very good, but it's not cool if it is not available in PRs. But according to Travis docs, encrypted variables are not available only for the forks (other repos). So should be fine in our repo, right?

When thinking about S3, I had in mind having public links pushed in the travis log, so you can in browser open file in a text format without auth. Unsecure? Technically, only people with access to our Travis will be able to see those files, until they expire. Needing to go through AWS-auth and use AWS console looks very bad to me.

**Comment by andreineculau** [comment]
> But according to Travis docs, encrypted variables are not available only for the forks (other repos). So should be fine in our repo, right?

hmm, pretty sure the docs were saying smth else when I wrote this function https://github.com/tobiipro/support-firecloud/blob/9954356/repo/dot.travis.sh.sf#L43-L57 cuz I wanted to mimic travis behaviour, but we are more strict right now

so yeah, you're right

> having public links pushed in the travis log

I remembered what is off with this setup - we turned into https://www.file.io :)
with a public-write but auth-reads, not only we have it more secure, but we also remove the incentive of using this bucket for obscure purposes :(

**Comment by andreineculau** [comment]
One thing to keep in mind is that we have no means to restrict sizes of S3 PUT requests.
So I could start using the bucket as my temporary netflix 😉

**Comment by IanSavchenko** [comment]
You can use GitHub as your Netflix ;)

**Comment by andreineculau** [comment]
> You can use GitHub as your Netflix ;)

you mean the github flow in this solution? no, not really - you have authenticated writes

---

I have pushed 32411c7 to go back to auth reads on S3. I personally don't want to take the responsibility for having non-auth writes and reads.

And actually I would even disable the S3 solution altogether and say "if you want travis job artifacts, then you need a GH_TOKEN in your repo" - so by default all of our big repos would just work, and the smaller ones, it might be that they never need job artifacts.

If we agree on the git refs solution, but not the S3 one, I can split this and we move ahead only with git refs for now (important to have some solution for gs-server on github).

PS: the current diff takes care of git refs lifecycle as well.

**Comment by IanSavchenko** [comment]
I'm ok with either solution, don't think that we need both. The only thing I don't like about S3 is the long auth flow, but hopefully, we won't need to debug our builds that often. So I leave it up to you, Andrei.

**Comment by andreineculau** [comment]
:+1: we can go github only (only private repos) for a while, and see if it's good enough

**Pull request merged**
