### PR TITLE
docs: increased protection for master branch

### PR DESCRIPTION
**Pull request by andreineculau**
https://github.com/tobiipro/support-firecloud/pull/61#issuecomment-448604637

### CODE REVIEW

**Comment by andreineculau** [comment]
I removed "include administrators" because that means nobody can "git push" straight to master... 🤔

**Comment by andreineculau** [comment]
This is how it looks with some new commits on the destination branch

screenshot 2018-12-19 at 15 44 58

**Comment by IanSavchenko** [comment]
Should we also allow only one merge strategy "Create a merge commit" (Merge button section in Settings)?

**Comment by andreineculau** [comment]
done. PR updated. now Luca awaits 🏃

**Comment by andreineculau** [comment]
ping @tobiiasl I leave it to you to enforce the settings on gs-client

**Pull request merged**
